# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerId: nickrossbrown
  imageName: call-your-moms 

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- script: docker build -t $(dockerId)/$(imageName) .
    npm install
    npm run build
  displayName: 'npm install and build'
